apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: gloo-mesh-ui-delegate-rt
  namespace: gloo-mesh
spec:
  http:
  - name: gloo-mesh-ui
    labels:
    matchers:
    - uri:
        prefix: /
    forwardTo:
      destinations:
      - ref:
          name: gloo-mesh-ui
          namespace: gloo-mesh
        port:
          number: 8090