apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: ops-routetable-80
  namespace: istio-gateways
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: north-south-gw
      namespace: istio-gateways
  http:
   - matchers:
     - uri:
         prefix: /
     delegate:
       routeTables:
         - name: gloo-mesh-ui-delegate-rt
           namespace: gloo-mesh